#!/usr/bin/env bash
# Phase 3: build a scrubbed anonymous review artifact package (local), audit identity leaks.
set -euo pipefail
REPO="/home/soroush/consistency-aware-llm-rankin"
OUT="$REPO/reports/jdiq-overnight-20260713-225928"
ART="$OUT/artifact_prep/anonymous_review_bundle"
STAGE="$OUT/artifact_prep/stage"
rm -rf "$ART" "$STAGE"
mkdir -p "$ART" "$STAGE"

echo "Building staged artifact contents..."

# Minimal reproducibility bundle: manuscript PDF (anonymous), key manifests, score inputs, scripts pointer,
# calibrated package tables — WITHOUT .git history and WITHOUT author-identifying README.

mkdir -p "$STAGE/manuscript" "$STAGE/inputs" "$STAGE/tables" "$STAGE/code_snapshot" "$STAGE/docs"

cp "$REPO/papers/JDIQ_2026/manuscript/main.pdf" "$STAGE/manuscript/"
cp "$REPO/papers/JDIQ_2026/manuscript/main.tex" "$STAGE/manuscript/"
cp "$REPO/papers/JDIQ_2026/manuscript/references.bib" "$STAGE/manuscript/"
cp -a "$REPO/papers/JDIQ_2026/manuscript/figures_v2" "$STAGE/manuscript/" 2>/dev/null || true
# strip pycache from figures copy
find "$STAGE/manuscript" -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true

# Score inputs + query ids (public benchmark scores generated by authors; include hashes for verification)
for ds in scidocs fiqa hotpotqa bright; do
  mkdir -p "$STAGE/inputs/$ds"
  src="$REPO/experiments/method_improvement_audit_20260711_205733/inputs/$ds"
  if [[ -d "$src" ]]; then
    cp -a "$src"/. "$STAGE/inputs/$ds/" || true
  fi
done

# Key calibrated tables (small)
TAB="$REPO/reports/full_calibrated_core/outputs/calibrated_all4/paper_package/tables"
if [[ -d "$TAB" ]]; then
  cp -a "$TAB"/. "$STAGE/tables/" || true
fi

# Code snapshot: selected reproducibility modules (not whole private reports tree)
mkdir -p "$STAGE/code_snapshot/src" "$STAGE/code_snapshot/reports_scripts"
rsync -a --exclude '__pycache__' --exclude '*.pyc' \
  "$REPO/src/consistency_ranker" "$STAGE/code_snapshot/src/" || true
cp "$REPO/reports/full_calibrated_core/scripts/"*.py "$STAGE/code_snapshot/reports_scripts/" 2>/dev/null || true
cp "$REPO/requirements.txt" "$STAGE/code_snapshot/" 2>/dev/null || true
cp "$REPO/pyproject.toml" "$STAGE/code_snapshot/pyproject.toml.raw" 2>/dev/null || true

# Anonymize package metadata / README for the bundle
cat > "$STAGE/README.md" <<'EOF'
# Anonymous review artifact — preference-graph repair measurement study

This bundle supports double-anonymous review of the accompanying manuscript.

## Contents
- `manuscript/` — TeX sources, PDF, figures
- `inputs/` — stored BM25 / TF-IDF / MiniLM scores and query-ID lists
- `tables/` — manuscript-ready calibrated tables
- `code_snapshot/` — ranking/repair/evaluation code needed to regenerate mechanical results

## Anonymity
Author identity, institutional affiliation, and public repository remotes are withheld.
Do not attempt to deanonymize during review.

## Reproduction (high level)
1. Install Python >=3.11 and dependencies from `code_snapshot/requirements.txt`.
2. Use stored inputs under `inputs/` (do not regenerate upstream retrieval).
3. Follow manifests in `tables/` / manuscript Data Availability section for seeds and protocols.

Bootstrap seed 13; permutation seed 17; 10,000 resamples each (manuscript Experimental Setup).
EOF

# Scrub authorish strings from pyproject copy
if [[ -f "$STAGE/code_snapshot/pyproject.toml.raw" ]]; then
  python3 - <<'PY'
from pathlib import Path
p = Path("/home/soroush/consistency-aware-llm-rankin/reports/jdiq-overnight-20260713-225928/artifact_prep/stage/code_snapshot/pyproject.toml.raw")
t = p.read_text()
for pat in ["Soroush", "Vahidi", "soroush", "github.com/SoroushVahidi"]:
    t = t.replace(pat, "REDACTED")
# rewrite authors/email fields if present
import re
t = re.sub(r'(authors?\s*=\s*\[[^\]]*\])', 'authors = [{ name = "Anonymous", email = "anonymous@example.com" }]', t, flags=re.I)
Path(str(p).replace('.raw','')).write_text(t)
p.unlink(missing_ok=True)
print("scrubbed pyproject")
PY
fi

# Identity leakage scan before zip
python3 - <<'PY'
from pathlib import Path
root = Path("/home/soroush/consistency-aware-llm-rankin/reports/jdiq-overnight-20260713-225928/artifact_prep/stage")
needles = [
    "Soroush", "Vahidi", "soroush@", "github.com/SoroushVahidi",
    "/home/soroush/", "njit", "NJIT", "Author: Soroush",
]
hits = []
for p in root.rglob("*"):
    if p.is_dir():
        continue
    if p.suffix.lower() in {".png", ".pdf", ".pkl", ".npy", ".npz"}:
        # still scan pdf/text lightly for pdf as binary string
        try:
            data = p.read_bytes()
        except Exception:
            continue
        for n in needles:
            if n.encode() in data:
                hits.append((str(p.relative_to(root)), n))
        continue
    try:
        text = p.read_text(errors="ignore")
    except Exception:
        continue
    for n in needles:
        if n in text:
            hits.append((str(p.relative_to(root)), n))
out = Path("/home/soroush/consistency-aware-llm-rankin/reports/jdiq-overnight-20260713-225928/artifact_prep/IDENTITY_LEAK_SCAN.txt")
if hits:
    out.write_text("LEAKS FOUND:\n" + "\n".join(f"{a}\t{b}" for a,b in hits) + "\n")
    print(f"WARNING: {len(hits)} identity leak hits; see IDENTITY_LEAK_SCAN.txt")
else:
    out.write_text("No identity needles found in staged bundle text/binary scan.\n")
    print("Identity scan clean for needle list.")
PY

# Remove PDF creator authorship if any via exiftool if available; else note
if command -v exiftool >/dev/null 2>&1; then
  exiftool -overwrite_original -all:all= -tagsFromFile @ -title -subject \
    "$STAGE/manuscript/main.pdf" >/dev/null 2>&1 || true
  echo "exiftool cleared PDF metadata where possible"
else
  echo "exiftool not installed; PDF metadata not scrubbed at binary tag level" | tee \
    "$OUT/artifact_prep/PDF_METADATA_NOTE.txt"
fi

# Package without .git
(
  cd "$STAGE"
  tar -czf "$ART/anonymous_review_artifact.tar.gz" .
)
(
  cd "$STAGE"
  zip -qr "$ART/anonymous_review_artifact.zip" .
)

# Manifest
python3 - <<'PY'
import hashlib, json
from pathlib import Path
art = Path("/home/soroush/consistency-aware-llm-rankin/reports/jdiq-overnight-20260713-225928/artifact_prep/anonymous_review_bundle")
man = {}
for p in art.iterdir():
    if p.is_file():
        h = hashlib.sha256(p.read_bytes()).hexdigest()
        man[p.name] = {"bytes": p.stat().st_size, "sha256": h}
Path("/home/soroush/consistency-aware-llm-rankin/reports/jdiq-overnight-20260713-225928/artifact_prep/ARTIFACT_MANIFEST.json").write_text(json.dumps(man, indent=2)+"\n")
print(man)
PY

cat > "$OUT/artifact_prep/UPLOAD_INSTRUCTIONS.md" <<'EOF'
# Anonymous artifact upload instructions

Local scrubbed packages are ready under `anonymous_review_bundle/`.

## Still required (manual / interactive)

1. Create an `https://anonymous.4open.science` (or equivalent) project.
2. Upload `anonymous_review_artifact.zip` **or** a fresh git-export with no remotes/history.
3. Confirm reviewers cannot see author IP tracking and that clone URL does not redirect to identifying GitHub.
4. Re-scan the hosted copy for: Git history, remotes, commit authors, README identity, package metadata, PDF metadata, absolute local paths, author names, badges, user-specific URLs.
5. Insert only the verified anonymous URL into the manuscript Data Availability section after it exists.
6. Do **not** put `github.com/SoroushVahidi/...` in the anonymous PDF.

## What this overnight job produced

- Local anonymous bundle (tar.gz + zip)
- Identity needle scan report
- SHA256 manifest
EOF

ls -lh "$ART"
echo "Phase 3 complete."
